
services:
  backend:
    build:
      context: .
      dockerfile: AnalyticsBackend/Dockerfile
    container_name: analytics_backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=AstraZenekaTest;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: analytics-frontend/Dockerfile
    container_name: analytics_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"                    
      MSSQL_PID: "Express"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -Q 'SELECT 1' -No"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    ports:
      - "1433:1433"